/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cwzeng' at '8/31/16 11:19 AM' with Gradle 2.14
 *
 * @author cwzeng, @date 8/31/16 11:19 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
